# notifyStaff - Notifies staff members when a new request is filed.
# notifySound - If true, a notification sound will be played when requests are created.
# hideMessageIfEmpty - If true, hides the notification on login if there are no open requests.
# debug - If true, it will show information about actions performed.
# VanishSupport - If true, hide staff from /modlist when vanished.
# command.legacy - If true, use old command system. I.e. /check, /complete, /modreq etc.
# versionCheck - If true, ReportRTS will alert you of new recommended versions.
# ticket.max - Maximum number of tickets a user may have open at the same time.
# ticket.delay - User has to wait this amount of seconds before opening another ticket.
# ticket.hideOffline - If set to true, hides all tickets in /ticket read from offline users.
# ticket.perPage - This sets the total amount of tickets that should be shown on each page.
# ticket.preventDuplicates - Prevent duplicate tickets by the same user.
# ticket.nag - If above 0 (minutes), nag the online staff members about open tickets.
# ticket.nagHeld - If true, the nag feature will mention tickets on hold. !!This will run a DB query!!
# storage - Setup for storage in ReportRTS. Supported types: MySQL.
# bungeecord.enable - If true, BungeeCord support will be enabled.
# bungeecord.sync - Sync timer in seconds.
# bungeecord.serverPrefix - Sets a prefix for the current server.
# bungeecord.serverName - !!!!DO NOT TOUCH!!!!. Server name as it appears in the BungeeCord config.
# api.enable - Enables the API server in ReportRTS which may be used to remotely control ReportRTS.
# api.port - Sets the port that the ReportRTS API server will listen to.
# api.password - Sets a password to authenticate your connection to the API server.
# api.whitelist - A list of allowed IPs that may connect. Disabled if set to 0.0.0.0 or [].

notifyStaff: true
notifySound: true
hideMessageIfEmpty: false
debug: false
VanishSupport: false
versionCheck: true

command:
  legacy: false
  readTicket: 'read'
  openTicket: 'open'
  closeTicket: 'close'
  reopenTicket: 'reopen'
  claimTicket: 'claim'
  assignTicket: 'assign'
  unclaimTicket: 'unclaim'
  holdTicket: 'hold'
  teleportToTicket: 'tp'
  broadcastToStaff: 'broadcast'
  listStaff: 'staff'

ticket:
  delay: 60
  max: 5
  hideOffline: false
  perPage: 5
  preventDuplicates: true
  nag: 5
  nagHeld: false
  minimumWords: 3
  fancify: true

storage:
  type: mysql
  hostname: 'localhost'
  port: 3306
  database: 'minecraft'
  username: 'username'
  password: 'password'
  prefix: ''
  refreshTime: 600

api:
  enable: false
  port: 25567
  password: 'changeMe'
  whitelist:
    - 0.0.0.0

bungeecord:
  enable: false
  sync: 300
  serverPrefix: 'ChangeMe'
  serverName: ''