# notifyStaff - Notifies staff members when a new request is filed.
# hideMessageIfEmpty - If true, hides the notification on login if there are no open requests.
# debug - If true, it will show information about actions performed.
# mysql.enable - If true, uses MySQL instead of SQLite.
# request.max - Maximum number of requests a user may have open at the same time.
# request.delay - User has to wait this amount of seconds before filing another request.
# request.hideOffline - If set to true, hides all requests in /check from offline users.
# request.perPage - This sets the amount of requests that should be shown on each page.
# request.nag - If above 0 (minutes), nag the online staff members about open requests.

notifyStaff: true
hideMessageIfEmpty: false
debug: false

request:
  delay: 60
  max: 5
  hideOffline: false
  perPage: 5
  nag: 5

mysql:
  enable: false
  hostname: 'localhost'
  port: 3306
  database: 'minecraft'
  username: 'username'
  password: 'password'