name: ${name}
main: com.nyancraft.reportrts.ReportRTS
version: ${version}
author: ProjectInfinity
softdepend: [Vault, ProtocolLib]
commands:
  ticket:
    description: General user commands for ReportRTS
    usage: /<command> [action] [arguments]
  reportrts:
    description: General management commands for ReportRTS
    aliases: [rts]
    usage: /<command> [reload | ban | unban | reset | stats <player> | help | notifications | duty | find <completed|created>]
permissions:
  reportrts.user:
    description: Give this to all of your regular players.
    default: true
    children:
      reportrts.command.modreq: true
      reportrts.command.check.self: true
      reportrts.command.complete.self: true
  reportrts.mod:
    description: Give this to all staff members.
    default: op
  reportrts.override:
    description: Permission to override the actions of other staff members.
    default: op
  reportrts.command.modreq:
    description: Permission to file a request.
    default: op
  reportrts.command.modreq.unlimited:
    description: Permission to file unlimited amounts of requests.
    default: op
  reportrts.command.check:
    description: Permission to check all requests.
    default: op
  reportrts.command.check.self:
    description: Permission to check your own requests.
    default: op
  reportrts.command.complete:
    description: Permission to complete and reopen requests.
    default: op
  reportrts.command.complete.self:
    description: Permission to complete your own requests.
    default: op
  reportrts.command.teleport:
    description: Permission to teleport to requests.
    default: op
  reportrts.command.reload:
    description: Permission to reload configuration.
    default: op
  reportrts.command.reset:
    description: Permission to reset the plugin.
    default: op
  reportrts.command.stats:
    description: Permission to look up staff stats.
    default: op
  reportrts.command.ban:
    description: Permission to ban people from ReportRTS.
    default: op
  reportrts.command.hold:
    description: Permission to put requests on hold.
    default: op
  reportrts.command.claim:
    description: Permission to claim and unclaim requests.
    default: op
  reportrts.command.modlist:
    description: Permission to use modlist.
    default: op
  reportrts.command.broadcast:
    description: Permission to broadcast to staff.
    default: op
  reportrts.command.help:
    description: Permission to see the help page.
    default: op
  reportrts.command.notifications:
    description: Permission to manage notifications.
    default: op
  reportrts.command.assign:
    description: Permission to assign requests.
    default: op