name: ReportRTS
main: com.nyancraft.reportrts.ReportRTS
version: 0.2
author: ProjectInfinity
softdepend: [Vault]
commands:
  modreq:
    description: Request help from staff
    usage: /<command> [message]
  check:
    description: Check all requests.
    usage: /<command> [id | page <id> | p <id>]
  complete:
    description: Marks specified request as completed
    usage: /<command> [id]
    aliases: [done]
  tp-id:
    description: Teleports to the specified request
    usage: /<command> [id]
    aliases: [tpid]
  reportrts:
    description: General commands for ReportRTS
    usage: /<command> [reload | ban | unban | reset]
  hold:
    description: Puts the specified ticket on hold
    usage: /<command> [id]
  claim:
    description: Claims the specified ticket
    usage: /<command> [id]
  modlist:
    description: Shows online staff members
    usage: /<command>
  unclaim:
    description: Unclaims the specified ticket
    usage: /<command> [id]
  reopen:
    description: Reopens the specified ticket
    usage: /<command> [id]
  mod-broadcast:
    description: Broadcasts a message to staff
    usage: /<command> [message]
    aliases: [mb]
permissions:
  reportrts.mod:
    description: Give this to all staff members.
    default: op
  reportrts.command.modreq:
    description: Permission to file a request.
    default: op
  reportrts.command.check:
    description: Permission to check all requests.
    default: op
  reportrts.command.complete:
    description: Permission to complete and reopen requests.
    default: op
  reportrts.command.teleport:
    description: Permission to teleport to requests.
    default: op
  reportrts.command.reload:
    description: Permission to reload configuration.
    default: op
  reportrts.command.reset:
    description: Permission to reset the plugin.
    default: op
  reportrts.command.ban:
    description: Permission to ban people from ReportRTS.
    default: op
  reportrts.command.hold:
    description: Permission to put requests on hold.
    default: op
  reportrts.command.claim:
    description: Permission to claim and unclaim requests.
    default: op
  reportrts.command.modlist:
    description: Permission to use modlist.
    default: op
  reportrts.command.broadcast:
    description: Permission to broadcast to staff.
    default: op